version: "3.1"
services:
  php:
    build: .
    container_name: misgastos_apache-php
    ports:
      - 80:80
    # Las carga del fichero .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - ./web/:/var/www/html/misgastos/
  mysqldb:
    image: mysql:latest
    container_name: misgastos_mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data/:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: misgastos_phpmyadmin
    environment:
      - PMA_HOST=${MYSQL_HOST}
    ports:
      - 8080:80